### ISSUE TITLE
Run  make hw -f Makefile.fpga on devcloud for vector-add example error

### ISSUE THREAD

**Issue by yyd999** [oneapi-src/oneAPI-samples#803]
# Summary
**When I run "make hw -f Makefile.fpga" on devcloud, encourtered error**
**Error message is:**
```
u120263@s001-n064:~/oneAPI-samples/DirectProgramming/DPC++/DenseLinearAlgebra/vector-add$ make hw -f Makefile.fpga
dpcpp -O2 -g -std=c++17 -fintelfpga a.o -o vector-add-buffers.fpga -Xshardware
aoc: Compiling for FPGA. This process may take several hours to complete.  Prior to performing this compile, be sure to check the reports to ensure the design will meet your performance targets.  If the reports indicate performance targets are not being met, code edits may be required.  Please refer to the oneAPI FPGA Optimization Guide for information on performance tuning applications for FPGAs.
Error (23035): Tcl error:
Error (23031): Evaluation of Tcl script build/entry.tcl unsuccessful
Error: Quartus Prime Shell was unsuccessful. 2 errors, 0 warnings
For more details, full Quartus compile output can be found in files quartuserr.tmp and quartus_sh_compile.log.
Error: Compiler Error, not able to generate hardware

llvm-foreach:
dpcpp: error: fpga compiler command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile.fpga:30: vector-add-buffers.fpga] Error 1
```
**cat qurartuserr.tmp file:**

```
u120263@s001-n064:~/oneAPI-samples/DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/vector-add-buffers.fpga.prj$ cat quartuserr.tmp
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./tools/packager.pyz/__main__.py", line 28, in <module>
  File "./tools/packager.pyz/packager.py", line 35, in <module>
  File "./tools/packager.pyz/afu.py", line 52, in <module>
  File "./tools/packager.pyz/jsonschema-2.3.0/jsonschema/__init__.py", line 18, in <module>
  File "./tools/packager.pyz/jsonschema-2.3.0/jsonschema/validators.py", line 161, in <module>
  File "./tools/packager.pyz/jsonschema-2.3.0/jsonschema/_utils.py", line 61, in load_schema
IOError: [Errno 20] Not a directory: u'/home/u120263/tmp/a-efc277-afbbc6/build/tools/packager.pyz/jsonschema-2.3.0/jsonschema/schemas/draft3.json'
------------------------------------------------

    while executing
"qexec "bash build/run.sh $revision_name""
    ("default" arm line 9)
    invoked from within
"switch $tcl_platform(platform) {
  windows {
    post_message -type error "Full compiles to generate hardware for the FPGA are available on supported ..."
    (file "build/entry.tcl" line 36)
------------------------------------------------
```

# Version
devcloud current oneAPI version

# Environment
devcloud fpga_compile node

# Steps to reproduce
run "make hw -f Makefile.fpga" on devcloud in interactive mode

**Comment by yyd999** [comment]
Wrong Node used
